import { DashboardShell } from '@/components/DashboardShell';import { BarChart3, Bell, Camera, Check, Clock3, MessageCircle, Plus, Search, Settings, Star, UserRound, UsersRound } from 'lucide-react';
const config:Record<string,{title:string;subtitle:string;icon:any;stats:[string,string][]}>={
 rdv:{title:'Rendez-vous',subtitle:'Recherche, filtres et gestion de toutes tes réservations',icon:Clock3,stats:[['À venir','18'],['Terminés ce mois','126'],['Annulés','7']]},
 'file-attente':{title:'File d’attente',subtitle:'Gère les clients sans rendez-vous en temps réel',icon:UsersRound,stats:[['Dans la file','3'],['Attente estimée','42 min'],['Servis aujourd’hui','8']]},
 clients:{title:'Fichier clients',subtitle:'Historique, préférences et fidélité de tes habitués',icon:UserRound,stats:[['Clients actifs','284'],['Nouveaux ce mois','27'],['Habitués','96']]},
 portfolio:{title:'Portfolio',subtitle:'Publie les vraies coupes réalisées au salon',icon:Camera,stats:[['Photos publiées','24'],['À modérer','2'],['Vues ce mois','1 842']]},
 avis:{title:'Avis clients',subtitle:'Lis et réponds aux avis vérifiés',icon:Star,stats:[['Note moyenne','4,9'],['Avis vérifiés','68'],['Sans réponse','2']]},
 statistiques:{title:'Statistiques',subtitle:'Comprends ton chiffre d’affaires et ton remplissage',icon:BarChart3,stats:[['CA ce mois','8 420 MAD'],['Remplissage','78 %'],['Panier moyen','47 MAD']]},
 parametres:{title:'Paramètres',subtitle:'Profil professionnel, notifications et sécurité',icon:Settings,stats:[['Profil complété','92 %'],['WhatsApp','Connecté'],['Langue','Français']]}
};
export default async function ProModule({params}:{params:Promise<{module:string}>}){const{module}=await params;const x=config[module]||config.parametres;const Icon=x.icon;return <DashboardShell title={x.title} subtitle={x.subtitle}><div className="dash-content generic-module"><div className="generic-stats">{x.stats.map(s=><div key={s[0]}><span>{s[0]}</span><b>{s[1]}</b></div>)}</div><section><header><div><Icon/><span><b>{x.title}</b><small>Données synchronisées en temps réel</small></span></div><button><Plus/> Ajouter</button></header><div className="generic-search"><Search/><input placeholder={`Rechercher dans ${x.title.toLowerCase()}…`}/><button>Filtres</button></div>{module==='file-attente'?<div className="queue-demo">{[['1','Amine','Coupe homme','~ 12 min'],['2','Sofiane','Dégradé','~ 38 min'],['3','Mehdi','Barbe','~ 52 min']].map(q=><article key={q[0]}><b>{q[0]}</b><span><strong>{q[1]}</strong><small>{q[2]}</small></span><em>{q[3]}</em><button>Appeler</button></article>)}</div>:<div className="module-rows">{['Activité récente','Éléments nécessitant ton attention','Historique du Salon Mouad'].map((r,i)=><article key={r}><span><Check/></span><p><b>{r}</b><small>Mis à jour {i===0?'à l’instant':`il y a ${i+1} h`}</small></p><button>Consulter</button></article>)}</div>}</section></div></DashboardShell>}
