'use client';
import { ReactNode,useState } from 'react';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { Logo } from './Logo';
import { BarChart3, Bell, CalendarDays, ChevronDown, Clock3, Image, LayoutDashboard, LogOut, Menu, MessageSquare, Scissors, Settings, ShieldCheck, Star, Store, UsersRound, UserCheck, WalletCards, X } from 'lucide-react';
const proItems=[['/pro','Aujourd’hui',LayoutDashboard],['/pro/agenda','Agenda',CalendarDays],['/pro/rdv','Rendez-vous',Clock3],['/pro/file-attente','File d’attente',UsersRound],['/pro/services','Services',Scissors],['/pro/horaires','Horaires',Clock3],['/pro/clients','Clients',UserCheck],['/pro/portfolio','Portfolio',Image],['/pro/avis','Avis',Star],['/pro/statistiques','Statistiques',BarChart3],['/pro/profil','Mon profil',UserCheck]] as const;
const adminItems=[['/admin','Vue d’ensemble',LayoutDashboard],['/admin/validations','Validations',ShieldCheck],['/admin/salons','Salons',Store],['/admin/coiffeurs','Coiffeurs',Scissors],['/admin/utilisateurs','Utilisateurs',UsersRound],['/admin/rdv','Rendez-vous',CalendarDays],['/admin/moderation','Modération',MessageSquare],['/admin/analytique','Analytique',BarChart3],['/admin/facturation','Facturation',WalletCards],['/admin/parametres','Paramètres',Settings]] as const;
export function DashboardShell({children,type='pro',title,subtitle}:{children:ReactNode,type?:'pro'|'admin',title:string,subtitle:string}){
 const pathname=usePathname();const items=type==='pro'?proItems:adminItems;const[menuOpen,setMenuOpen]=useState(false);
 return <div className="dash"><button className={'dash-overlay '+(menuOpen?'show':'')} onClick={()=>setMenuOpen(false)} aria-label="Fermer le menu"/><aside className={'dash-side '+(menuOpen?'mobile-open':'')}><div className="dash-logo"><Logo/>{type==='admin'&&<small>ADMIN</small>}<button className="dash-side-close" onClick={()=>setMenuOpen(false)}><X/></button></div><nav>{items.map(([href,label,Icon])=><Link onClick={()=>setMenuOpen(false)} className={href==='/admin'||href==='/pro'?pathname===href?'active':'':pathname.startsWith(href)?'active':''} href={href} key={label}><Icon/>{label}{label==='Validations'&&<b>4</b>}</Link>)}</nav><div className="side-bottom"><Link href={type==='admin'?'/admin/parametres':'/pro/parametres'}><Settings/> Paramètres</Link><Link href="/api/v1/auth/logout"><LogOut/> Se déconnecter</Link><div className="side-user"><span>{type==='admin'?'MG':'KM'}</span><p><b>{type==='admin'?'Mourad Ghazi':'Karim B.'}</b><small>{type==='admin'?'Super-Admin':'Salon Mouad'}</small></p><ChevronDown/></div></div></aside><main className="dash-main"><header><button className="dash-menu" onClick={()=>setMenuOpen(true)} aria-label="Ouvrir le menu"><Menu/></button><div><h1>{title}</h1><p>{subtitle}</p></div><section><button aria-label="Notifications"><Bell/><i>3</i></button><div className="online"><i/> {type==='admin'?'Système opérationnel':'Salon ouvert'}</div></section></header>{children}</main></div>
}
