'use client';
import { useEffect,useRef,useState } from 'react';import { Check,Languages } from 'lucide-react';
export type Lang='fr'|'ary'|'ar'|'en';
const options:{code:Lang;label:string;native:string;dir:'ltr'|'rtl'}[]=[{code:'fr',label:'Français',native:'FR',dir:'ltr'},{code:'ary',label:'Darija',native:'الدارجة',dir:'rtl'},{code:'ar',label:'Arabe',native:'العربية',dir:'rtl'},{code:'en',label:'English',native:'EN',dir:'ltr'}];
const translations:Record<Lang,Record<string,string>>={
 fr:{salons:'Salons',inspirations:'Inspirations',pro:'Espace pro',partner:'Devenir partenaire',login:'Se connecter',book:'Réserver',welcome:'Se connecter',rolePrompt:'Choisis comment tu utilises HLAQTI.',client:'Je suis client',clientSub:'Je réserve ma coupe',barber:'Je suis coiffeur',barberSub:'Je gère mon activité',phone:'NUMÉRO WHATSAPP',sendCode:'Recevoir mon code'},
 ary:{salons:'الصالونات',inspirations:'قصّات وأفكار',pro:'فضاء الحلاق',partner:'ولي شريك معنا',login:'دخل لحسابك',book:'حجز دابا',welcome:'دخل لحسابك',rolePrompt:'اختار كيفاش غادي تستعمل حلاقتي.',client:'أنا زبون',clientSub:'بغيت نحجز الحلاقة',barber:'أنا حلاق',barberSub:'بغيت نسير الخدمة ديالي',phone:'رقم الواتساب',sendCode:'صيفط ليا الكود'},
 ar:{salons:'الصالونات',inspirations:'الإلهام',pro:'فضاء الحلاق',partner:'كن شريكاً',login:'تسجيل الدخول',book:'احجز الآن',welcome:'تسجيل الدخول',rolePrompt:'اختر كيفية استخدام حلاقتي.',client:'أنا عميل',clientSub:'أريد حجز موعد',barber:'أنا حلاق',barberSub:'أدير نشاطي المهني',phone:'رقم واتساب',sendCode:'أرسل رمز التحقق'},
 en:{salons:'Salons',inspirations:'Inspiration',pro:'Pro dashboard',partner:'Become a partner',login:'Sign in',book:'Book now',welcome:'Sign in',rolePrompt:'Choose how you use HLAQTI.',client:'I am a client',clientSub:'I want to book a cut',barber:'I am a barber',barberSub:'I manage my business',phone:'WHATSAPP NUMBER',sendCode:'Send my code'}
};
function apply(lang:Lang){const option=options.find(x=>x.code===lang)!;document.documentElement.lang=lang;document.documentElement.dir=option.dir;document.cookie=`hlaqti_lang=${lang};path=/;max-age=31536000;samesite=lax`;localStorage.setItem('hlaqti_lang',lang);document.querySelectorAll<HTMLElement>('[data-i18n]').forEach(el=>{const key=el.dataset.i18n!;const value=translations[lang][key];if(value)el.textContent=value});window.dispatchEvent(new CustomEvent('hlaqti-language',{detail:lang}))}
export function LanguageSwitcher({dark=true}:{dark?:boolean}){const[open,setOpen]=useState(false);const[lang,setLang]=useState<Lang>('fr');const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const saved=(localStorage.getItem('hlaqti_lang')||'fr') as Lang;setLang(saved);apply(saved);const close=(e:MouseEvent)=>{if(!ref.current?.contains(e.target as Node))setOpen(false)};document.addEventListener('mousedown',close);return()=>document.removeEventListener('mousedown',close)},[]);const current=options.find(x=>x.code===lang)!;return <div className={'language-switcher '+(!dark?'light':'')} ref={ref}><button onClick={()=>setOpen(!open)} aria-expanded={open}><Languages/>{current.native}<span>⌄</span></button>{open&&<div>{options.map(x=><button key={x.code} className={lang===x.code?'active':''} onClick={()=>{setLang(x.code);apply(x.code);setOpen(false)}}><span>{x.native}</span><b>{x.label}</b>{lang===x.code&&<Check/>}</button>)}</div>}</div>}
